version: '3.4'

services:

  podcast.api:
    environment:
        #- ConnectionStrings__PodcastDb=Server=podcast.db;Database=Podcast;User Id=sa;Password=Pass@word;Encrypt=False
        - ConnectionStrings__PodcastDb=Host=podcast.db;Database=Podcast;Username=sa;Password=Pass@word
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - ConnectionStrings__FeedQueue=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://azurite
        - AZURE_KEY_VAULT_ENDPOINT=https://podcastvault.vault.azure.net/
        - AZURE_API_SQL_CONNECTION_STRING_KEY=''
    ports:
        - "5003:80"

#  podcast.db:
#    environment:
#      - SA_PASSWORD=Pass@word
#     - ACCEPT_EULA=Y
#   ports:
#     - "5433:1433"
#   volumes:
#     - podcast-sqldata:/var/opt/mssql

  podcast.db:
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Pass@word
      POSTGRES_DB: Podcasts
      PGDATA: /var/lib/postgresql/data/mydata/
    #volumes:
    #  - 'podcast-sqldata:/var/lib/postgresql/data/mydata/'
    ports:
      - "5432:5432"

  podcast.updater.worker:
    environment:
      - ConnectionStrings__PodcastDb=Server=podcast.db;Database=Podcast;User Id=sa;Password=Pass@word;Encrypt=False

  podcast.ingestion.worker:
    environment:
      - ConnectionStrings__PodcastDb=Server=podcast.db;Database=Podcast;User Id=sa;Password=Pass@word;Encrypt=False
      - ConnectionStrings__FeedQueue=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://azurite

  listentogether.hub:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - NetPodcastApi__BaseAddress=http://podcast.api
      - ConnectionStrings__ListenTogetherDb=Server=podcast.db;Database=ListenTogether;User Id=sa;Password=Pass@word;Encrypt=False
      - ConnectionStrings__OrleansStorage=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://azurite
    ports:
      - "5001:80"

  storage:
    hostname: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  podcast.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - PodcastApi__BaseAddress=http://podcast.api
      - ListenTogetherHub=http://listentogether.hub/listentogether
    ports:
    - "5002:80"

volumes:
  podcast-sqldata:
   # external: false